### ISSUE TITLE
CentOS builds fail

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#144]
I keep getting the following error when building packages for CentOS 7.x:

```
Enabling updates-source repository
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

failure: repodata/repomd.xml from base-source: [Errno 256] No more mirrors to try.
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Cleaning up self packagecore-96798e7643810165.
packagecore-96798e7643810165
packagecore-96798e7643810165

###########################################################
# Failed to build package for 'centos7.2'.
###########################################################
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/packagecore/packager.py", line 160, in run
    imageName=build["dockerImage"])
  File "/usr/local/lib/python3.4/dist-packages/packagecore/packager.py", line 102, in _build
    recipe.build(container)
  File "/usr/local/lib/python3.4/dist-packages/packagecore/rpm.py", line 216, in build
    container.execute(["/usr/bin/yum-builddep", "-y", self._specFile])
  File "/usr/local/lib/python3.4/dist-packages/packagecore/docker.py", line 149, in execute
    _checkedDockerCommand(["exec", self._name] + cmd)
  File "/usr/local/lib/python3.4/dist-packages/packagecore/docker.py", line 54, in _checkedDockerCommand
    raise DockerError("Command '%s' returned %d." % (cmd, status))
packagecore.docker.DockerError: Command '['exec', 'packagecore-96798e7643810165', '/usr/bin/yum-builddep', '-y', '/tmp/packagecore-96798e7643810165/pkg.spec']' returned 1.
```

Complete logs: http://paste.ubuntu.com/p/k8t7XqRvmY/

**Comment by jarun** [comment]
Any update on this?

**Comment by dlasalle** [comment]
Sorry, I'm in the process of moving currently. I'll try to take a look this weekend.

**Comment by jarun** [comment]
Thanks for the update!

**Comment by jarun** [comment]
Also, the package is not updated to release 0.9.9 in PyPi so I can't generate Fedora 28 packages either.

**Comment by dlasalle** [comment]
Just got 0.9.9 pushed into PyPI. Looking into this issue now.

**Comment by dlasalle** [comment]
Have you had this fail multiple times? I haven't been able to get a centos 7.2 build to fail, and am able to fetch the `repomod.xml` from the listed URL. I suspect since the docker image only has a baseserver listed and no mirrors for the `Sources` repo, this is just that the connection to the server failed.

We could add a parameter for 'retrying' to build a package if it fails, hopefullying successfully retreiving files in a subsequent try. However, I think in most cases it will just waste time without fixing anything (and may re-try when the failure is not do to a network error).

Unfortunately it looks like CentOS's mirror system only works for the most recent versions of major releases (e.g., you can get the mirrors for CentOS 7.5, but not 7.2).

Assuming re-starting your build works, I think I would be in favor of just manually re-running such failed builds. Please let me know if it continues to fail.
